name: Frontend CI

on:
  push:
    branches: [ main, master, PP-43-CI-CD-cevovod-z-GitHub-Actions ]
    paths: 
      - 'RAIN/frontend/**'
  pull_request:
    branches: [ main, master, PP-43-CI-CD-cevovod-z-GitHub-Actions ]
    paths:
      - 'RAIN/frontend/**'

jobs:
  test:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./RAIN/frontend

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: RAIN/frontend/package-lock.json 

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test