name: ORV CI Workflow

on:
  push:
    branches: [ master ]
    paths:
      - 'ORV/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'ORV/**'

jobs:
  test:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./ORV

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          python -m pip install pytest

      - name: Run Pytests
        run: |
          PYTHONPATH=. pytest src/tests