name: Run ORV Tests

on:
  push:
    branches: [ master ]
    paths:
      - 'ORV/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'ORV/**'

jobs:
  test:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: ./ORV

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libgl1-mesa-glx \
            libglib2.0-0
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run Pytests
        run: |
          PYTHONPATH=. pytest src/tests